!function(){const t=[{src:"/images/a.jpg",alt:"a"},{src:"/images/b.jpg",alt:"b"},{src:"/images/c.png",alt:"c"},{src:"/images/d.jpg",alt:"d"},{src:"/images/e.jpg",alt:"e"},{src:"/images/f.jpg",alt:"f"},{src:"/images/g.jpg",alt:"g"},{src:"/images/h.jpg",alt:"h"},{src:"/images/i.jpg",alt:"i"},{src:"/images/j.jpg",alt:"j"},{src:"/images/k.jpg",alt:"k"},{src:"/images/l.jpg",alt:"l"},{src:"/images/m.jpg",alt:"m"},{src:"/images/n.jpg",alt:"n"},{src:"/images/o.jpg",alt:"o"}],e=document.getElementById("canvas"),a=e.getContext("2d"),n=document.getElementById("indicators");let i=0,l=!1,o=null,c=null;const r=[];function s(){
// 获取 .my-swiper-wrapper 的宽度
const t=document.querySelector(".my-swiper-wrapper"),n=document.querySelector(".carousel-container");if(!t||!n)return;const o=t.getBoundingClientRect().width,c=n.getBoundingClientRect().height;
// Canvas 宽度 = wrapper 宽度，高度 = container 高度
e.width=o*devicePixelRatio,e.height=c*devicePixelRatio,e.style.width=o+"px",e.style.height=c+"px",a.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0),!l&&r[i]&&d(r[i])}function d(t,n){const i=n||a,l=e.width/devicePixelRatio,o=e.height/devicePixelRatio;if(0===l||0===o)return;const c=l/o;let r,s,d,g;t.naturalWidth/t.naturalHeight>c?(g=t.naturalHeight,d=g*c,r=(t.naturalWidth-d)/2,s=0):(d=t.naturalWidth,g=d/c,r=0,s=(t.naturalHeight-g)/2),i.drawImage(t,r,s,d,g,0,0,l,o)}function g(t,n,i){const l=e.width/devicePixelRatio,o=e.height/devicePixelRatio,r=Math.ceil(l/6),s=Math.ceil(o/6),g=function(t){const a=e.width/devicePixelRatio,n=e.height/devicePixelRatio,i=document.createElement("canvas");i.width=a,i.height=n;const l=i.getContext("2d"),o=a/n;let c,r,s,d;return t.naturalWidth/t.naturalHeight>o?(d=t.naturalHeight,s=d*o,c=(t.naturalWidth-s)/2,r=0):(s=t.naturalWidth,d=s/o,c=0,r=(t.naturalHeight-d)/2),l.drawImage(t,c,r,s,d,0,0,a,n),l.getImageData(0,0,a,n)}(t),h=[];for(let t=0;t<r;t++){const e=.3*(Math.abs(t-r/2)/(r/2))+.15*Math.random();h.push({delay:e,speed:.8+.6*Math.random(),trail:3+Math.floor(5*Math.random())})}const m=[];for(let t=0;t<s;t++){m[t]=[];for(let e=0;e<r;e++){const a=Math.min(6*e+3,l-1),n=Math.min(6*t+3,o-1),i=4*(Math.floor(n)*Math.floor(l)+Math.floor(a));m[t][e]={r:g.data[i]||0,g:g.data[i+1]||0,b:g.data[i+2]||0,fallen:!1,y:6*t,vy:0,opacity:1}}}const u=performance.now();c=requestAnimationFrame(function t(e){const g=e-u,f=Math.min(g/2200,1);a.clearRect(0,0,l,o),a.globalAlpha=Math.min(1,2*f),d(n),a.globalAlpha=1;let y=!0;for(let t=0;t<r;t++){const e=h[t],n=Math.max(0,(f-e.delay)/(1-e.delay))*(s+e.trail);for(let i=0;i<s;i++){const l=m[i][t];if(i<n&&!l.fallen&&(l.fallen=!0,l.vy=2*e.speed),l.fallen){l.vy+=.35*e.speed,l.y+=l.vy;const n=l.y-6*i;if(l.opacity=Math.max(0,1-n/(.7*o)),l.y<o+6&&l.opacity>.01&&(y=!1,a.globalAlpha=l.opacity,a.fillStyle=`rgb(${l.r}, ${l.g}, ${l.b})`,a.fillRect(6*t,l.y,5.5,5.5),l.opacity>.3&&l.vy>3)){a.globalAlpha=.2*l.opacity,a.fillStyle=`rgb(${Math.min(255,l.r+80)}, ${Math.min(255,l.g+80)}, ${Math.min(255,l.b+80)})`;for(let e=1;e<=2;e++)a.fillRect(6*t,l.y-6*e*.8,5.5,5.5)}}else y=!1,a.globalAlpha=1,a.fillStyle=`rgb(${l.r}, ${l.g}, ${l.b})`,a.fillRect(6*t,l.y,5.5,5.5)}}a.globalAlpha=1,f<1||!y?c=requestAnimationFrame(t):(a.clearRect(0,0,l,o),d(n),i())})}function h(t){if(l||t===i)return;l=!0;const e=n.querySelectorAll(".indicator");e[i].classList.remove("active"),e[t].classList.add("active"),g(r[i],r[t],()=>{i=t,l=!1})}function m(){h((i+1)%t.length)}function u(){h((i-1+t.length)%t.length)}function f(){y(),o=setInterval(m,9e3)}function y(){o&&(clearInterval(o),o=null)}async function p(){
// 等待 DOM 完全渲染
await new Promise(t=>setTimeout(t,100)),s(),window.addEventListener("resize",s),t.forEach((t,e)=>{const a=document.createElement("button");a.className="indicator "+(0===e?"active":""),a.addEventListener("click",()=>h(e)),n.appendChild(a)}),await function(){let e=0;return new Promise(a=>{t.forEach((n,i)=>{const l=new Image;l.crossOrigin="anonymous",l.onload=()=>{r[i]=l,e++,e===t.length&&a()},l.onerror=()=>{const l=document.createElement("canvas");l.width=1920,l.height=1080;const o=l.getContext("2d"),c=o.createLinearGradient(0,0,1920,1080);c.addColorStop(0,`hsl(${60*i+140}, 50%, 25%)`),c.addColorStop(1,`hsl(${60*i+170}, 50%, 15%)`),o.fillStyle=c,o.fillRect(0,0,1920,1080),o.fillStyle="#fff",o.font="48px sans-serif",o.textAlign="center",o.fillText(n.alt,960,540),r[i]=l,e++,e===t.length&&a()},l.src=n.src})})}(),d(r[0]),f()}
// 绑定按钮事件
const v=document.getElementById("prevBtn"),w=document.getElementById("nextBtn"),x=document.querySelector(".carousel-container");v&&v.addEventListener("click",()=>{u(),f()}),w&&w.addEventListener("click",()=>{m(),f()}),x&&(x.addEventListener("mouseenter",y),x.addEventListener("mouseleave",f)),document.addEventListener("keydown",t=>{"ArrowLeft"===t.key&&(u(),f()),"ArrowRight"===t.key&&(m(),f())}),document.addEventListener("visibilitychange",()=>{document.hidden?y():f()}),
// 如果页面已加载完成则直接初始化，否则等 DOM 加载完
"complete"===document.readyState||"interactive"===document.readyState?p():document.addEventListener("DOMContentLoaded",p)}();